import React from 'react';
import style from "./Historias.module.css"
const Historias = () => {
    return (
        <div>
            <div className={style.parrafo}><p>hoy la protagonista es konnan, con la nueva alministracion recien estrenada a las 6 de la tarde, nuestra wuerida mascola toma un baño obligado comn agua fria y jabon rey, vimpos colombia ganar 3-0 lo disfrutamos,  y al lllegar y sacar la basura  tubieron su pasro matutinoi por solpresa nos envontrsmos un perro con bosal  y nuestra hermosa y querida amiga connan hico especial el momento al ser noble con sus enemigos</p></div>
            <div className={style.parrafo}><p>hoy primer festivo del mañoñ 20222 disfrutando entre lamentos y risa la angustiante etapa del desempleo con el aelo cercano del exito a nuestros planes remotos cumplidos en junio en ese ambiente hoy despidiendonos del dia nuestra hermosa demonia perdida entre la sombras se pierde nos juega una de sus terribles trabesuras fijense ustedes que la muy sofisticada salta feliz al juguetes de basura que entre su imaginacion creia en conclusion el bnasurerio del barrio mientras la solucion mas oportuna es de dilbani vuando fue a darle un regaño dijimos con jaime que nos regresemos a casa para que asi la mugrosa regresara pero la dicha perra no regreso se quedo esperando sentada en el prado mientras los papas se fueron esperando que ellls regrese a casa sola pero jamas regreso  jaime salio a traerla  pero en ves de traerla la hizo ir mas lejos a otro parque donde se quedo parado por que las bacas no estaban </p></div>

            <div className={style.parrafo}><p>hoy primer festivo del año 20222 disfrutando entre lamentos y risa la angustiante etapa del desempleo con el aelo cercano del exito a nuestros planes remotos cumplidos en junio en ese ambiente hoy despidiendonos del dia nuestra hermosa demonia perdida entre la sombras se pierde nos juega una de sus terribles trabesuras fijense ustedes que la muy sofisticada salta feliz al juguetes de basura que entre su imaginacion creia en conclusion el bnasurerio del barrio mientras la solucion mas oportuna es de dilbani vuando fue a darle un regaño dijimos con jaime que nos regresemos a casa para que asi la mugrosa regresara pero la dicha perra no regreso se quedo esperando sentada en el prado mientras los papas se fueron esperando que ellls regrese a casa sola pero jamas regreso  jaime salio a traerla  pero en ves de traerla la hizo ir mas lejos a otro parque donde se quedo parado por que las bacas no estaban </p></div>
            <div>commit ejemplo</div>
            <div><p>pasamos una semana dicicil como muchas que hemos pasado la konnan se hizo de pop de gallina yt toco bañarla y secarla y la nezuko se sube en la mesa a comerce todo lo que encuentra y hacer desastres elllas nesesitan salir creoque los que fallamos nosotros que no les dedicamos el tiempo suficiente pensando en tantas cosas, proyectos pendientes que nos aleja dee ellas pero siempre que podemos dedicarles tiempo lo hace a un que fallamos en el intento como el segundo dia de abril cuando habiamos planeado llevarlas a un paseo chebre que puedan correr y ser libres como el viento, teniamos la direccion del lugar al cual hibamos a ir y cuando ibamos en el camino nos dimos cuenta que era una subiendola montaña y el carro no aguantaria y desidimos devolvernos no sabiamos que hacer por que enserio queriamos llevarlas a un lugar bonito buscamos y nada luego decidimos ir  un parque que es grande y resulta que no habia parqueadero sentiamos que todo termino pero luego envontra una dirreccion supuestamente una casacada, despues de dar un monton de vueltasd para llegar a la casa por qur el lugare queda a unos kilometros de la casa nos metimos por una carretera toda chiquita se miraba gente peligrosa y la callle estaba horrible nos regresamos y nos dirigimos por otra carretera ibamos bien hasta
                que miramos el lugar y no era lo que esperabamos no se piodia parquear era  de la carretera mas arribita no se podia parquear entonceas nos fimos mas arriba  aver si encontrabamos otra cosa y nada, hasta que al fin enconteramos un lugar del cual nos echaron por que el parqueadero era solo de chientes y nosotros solo estabamos de paso no pudimos ni caminar desidimos regresarnos hasta otro lugar y ahi ya pudimos parquear y caminar por prado a final de todo estubo bien lo disfrutamos ellla corrieron hasta que se cansaron fueron felices como nosotros    </p></div>
        </div>
    );
}

export default Historias;
